name: Simple Test

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, ci-helper!"

      - name: Show environment
        run: |
          echo "Current directory: $(pwd)"
          echo "User: $(whoami)"
          echo "Date: $(date)"
